### PR TITLE
Apply matrixStats 1.0.0 breaking change for 'useNames' default [PR against devel]

### PR DESCRIPTION
**Pull request by hpages**
All generic functions and methods defined in **MatrixGenerics** now set the `useNames` argument to `TRUE` instead of `NA` by default, for consistency with **matrixStats** 1.0.0. See https://github.com/Bioconductor/MatrixGenerics/issues/31 for a discussion of this change.

### CODE REVIEW

**Comment by PeteHaitch** [comment]
Alright, I've got PR for `devel` branch of **DelayedMatrixStats** ready to go (https://github.com/PeteHaitch/DelayedMatrixStats/pull/96).

**Comment by PeteHaitch** [comment]
@hpages This PR is good to go from my end.

**Comment by PeteHaitch** [comment]
@hpages gentle nudge - shall we merge?

**Comment by PeteHaitch** [comment]
Merged and pushed to Bioconductor's git server.

**Comment by hpages** [comment]
Thanks Pete. Sorry for the slow response, I'm travelling and with only intermittent access to the internet.

**Comment by PeteHaitch** [comment]
All good, I figured you were probably on holiday or otherwise busy :)

**Pull request merged**
